### ISSUE TITLE
How to create a dynamic route if possible

### ISSUE THREAD

**Issue by StefanoPernat** [qudo-lucas/svelte-router#2]
Hello Lucas, 
I'm new to svelte, I'm having a lot of fun using your awesome svelte-router.

I'd like to ask you if it's possible to create a **dynamic route** like /users/{id}

Can you point me to an example

Thanks
Stefano

**Comment by qudo-lucas** [comment]
Cool idea! What about if URL params were just added to the event object? Would that work?

Thanks,
Lucas Hugdahl
Founder
425-367-8665
qudocreative.io

**Comment by qudo-lucas** [comment]
Hello, would this cover your use case? I experimented with created a Map on the event object. 
```
// URL ->  http://localhost:5000/#/page-one?id=xxx-xxx&something=hello
{
    current: "page-one"
    event: {_event: {…}, data: {…}, name: "page-one"}
    params: Map(2)
        0: {"id" => "xxx-xxx"}
         key: "id"
         value: "xxx-xxx"
    1: {"something" => "hello"}
        key: "something"
        value: "hello"
}
```

This would allow you to do things like this, where you only call a function if a param exists. This example is also using a new feature where router is a store that you can subscribe to.
```
$" ({ current, event, params } = $router);
$: params.has("id") && myFunction(params.get("id"));
```

**Comment by StefanoPernat** [comment]
Thanks, this is exactly what I need

**Comment by qudo-lucas** [comment]
Sounds good. I will do a little more testing and try to get this in there tomorrow.

**Comment by qudo-lucas** [comment]
Thank you for your patience. Here is V2 that includes the functionality mentioned. Get v2 via `npm update`.
https://svelte-router.now.sh
